In [1]:
import pandas as pd
import os

# Directorio donde están los archivos CSV
directorio = './jira'

# Lista para almacenar los resultados
resultados = []

# Iterar sobre todos los archivos CSV en el directorio
for archivo in os.listdir(directorio):
    if archivo.endswith('.csv'):
        ruta_completa = os.path.join(directorio, archivo)
        
        # Leer el CSV
        df = pd.read_csv(ruta_completa)
        
        # Calcular los parámetros
        num_filas = len(df)
        num_atributos = len(df.columns)
        
        # Calcular LOC total (solo si existe la columna)
        loc = df['CountLineCode'].sum() if 'CountLineCode' in df.columns else 'N/A'

        # Calcular Defective Rate % para HeuBug y RealBug
        heu_defective_rate = 'N/A'
        real_defective_rate = 'N/A'
        
        if 'HeuBug' in df.columns:
            defective_rate_heubug = f"{round((df['HeuBug'].sum() / num_filas) * 100, 2)}%" if num_filas > 0 else "0%"
        
        if 'RealBug' in df.columns:
            defective_rate_realbug = f"{round((df['RealBug'].sum() / num_filas) * 100, 2)}%" if num_filas > 0 else "0%"
        # Guardar resultados
        resultados.append({
            'Archivo': archivo,
            'LOC': loc,
            'Attributes': num_atributos,
            'Number of rows': num_filas,
            'Defective rate % (HueBug)': defective_rate_heubug,
            'Defective rate % (RealBug)': defective_rate_realbug
        })

# Crear DataFrame con los resultados
df_resultados = pd.DataFrame(resultados)
df_resultados.sort_values(by='Archivo', inplace=True)
project_names = [
    'activemq',
    'derby',
    'groovy',
    'hbase',
    'hive',
    'jruby',
    'wicket'
]
df_resultados = df_resultados[df_resultados['Archivo'].str.contains('|'.join(project_names), case=False, na=False)]
df_resultados

,Archivo,LOC,Attributes,Number of rows,Defective rate % (HueBug),Defective rate % (RealBug)
3,activemq-5.0.0.csv,142586,70,1884,4.35%,15.55%
9,activemq-5.1.0.csv,153958,70,1970,7.06%,7.82%
0,activemq-5.2.0.csv,168809,70,2040,7.55%,10.74%
11,activemq-5.3.0.csv,192008,70,2367,6.0%,10.9%
28,activemq-5.8.0.csv,299774,70,3420,5.94%,6.02%
26,derby-10.2.1.6.csv,412591,70,1963,9.17%,33.67%
21,derby-10.3.1.4.csv,462979,70,2206,7.12%,30.33%
1,derby-10.5.1.1.csv,533660,70,2705,6.65%,14.16%
19,groovy-1_5_7.csv,74266,70,757,10.57%,3.43%
22,groovy-1_6_BETA_1.csv,84199,70,821,14.25%,8.53%
20,groovy-1_6_BETA_2.csv,90704,70,884,11.65%,8.6%
5,hbase-0.94.0.csv,246541,70,1059,6.52%,20.59%
13,hbase-0.95.0.csv,535541,70,1669,5.45%,22.95%
17,hbase-0.95.2.csv,534637,70,1834,6.22%,26.34%
29,hive-0.10.0.csv,355488,70,1560,3.33%,11.28%
31,hive-0.12.0.csv,563119,70,2662,1.73%,8.0%
2,hive-0.9.0.csv,287310,70,1416,3.74%,19.99%
7,jruby-1.1.csv,105992,70,731,22.02%,11.9%
4,jruby-1.4.0.csv,150511,70,978,20.45%,18.4%
16,jruby-1.5.0.csv,169556,70,1131,24.4%,7.25%
8,jruby-1.7.0.preview1.csv,238485,70,1614,10.1%,5.39%
24,wicket-1.3.0-beta2.csv,109554,70,1763,17.3%,7.37%
18,wicket-1.3.0-incubating-beta-1.csv,105741,70,1672,17.22%,6.04%
27,wicket-1.5.3.csv,165308,70,2578,3.61%,4.07%

activemq-5.0.0.csv
derby-10.5.1.1.csv
groovy-1_6_BETA_1.csv
hbase-0.94.0.csv
hive-0.9.0.csv
jruby-1.1.csv
wicket-1.3.0-beta2.csv

In [2]:
archivos_a_filtrar = [
    'activemq-5.0.0.csv',
    'activemq-5.8.0.csv',
    'derby-10.2.1.6.csv',
    'derby-10.5.1.1.csv',
    'groovy-1_5_7.csv',
    'groovy-1_6_BETA_1.csv',
    'hbase-0.94.0.csv',
    'hbase-0.95.2.csv',
    'hive-0.9.0.csv',
    'hive-0.12.0.csv',
    'jruby-1.1.csv',
    'jruby-1.7.0.preview1.csv',
    'wicket-1.3.0-beta2.csv',
    'wicket-1.5.3.csv'
]

df_filtrado = df_resultados[df_resultados['Archivo'].isin(archivos_a_filtrar)]
df_filtrado

,Archivo,LOC,Attributes,Number of rows,Defective rate % (HueBug),Defective rate % (RealBug)
3,activemq-5.0.0.csv,142586,70,1884,4.35%,15.55%
28,activemq-5.8.0.csv,299774,70,3420,5.94%,6.02%
26,derby-10.2.1.6.csv,412591,70,1963,9.17%,33.67%
1,derby-10.5.1.1.csv,533660,70,2705,6.65%,14.16%
19,groovy-1_5_7.csv,74266,70,757,10.57%,3.43%
22,groovy-1_6_BETA_1.csv,84199,70,821,14.25%,8.53%
5,hbase-0.94.0.csv,246541,70,1059,6.52%,20.59%
17,hbase-0.95.2.csv,534637,70,1834,6.22%,26.34%
31,hive-0.12.0.csv,563119,70,2662,1.73%,8.0%
2,hive-0.9.0.csv,287310,70,1416,3.74%,19.99%
7,jruby-1.1.csv,105992,70,731,22.02%,11.9%
8,jruby-1.7.0.preview1.csv,238485,70,1614,10.1%,5.39%
24,wicket-1.3.0-beta2.csv,109554,70,1763,17.3%,7.37%
27,wicket-1.5.3.csv,165308,70,2578,3.61%,4.07%

In [3]:
archivos_a_filtrar = [
    'activemq-5.0.0.csv',
    'derby-10.5.1.1.csv',
    'groovy-1_6_BETA_1.csv',
    'hbase-0.94.0.csv',
    'hive-0.9.0.csv',
    'jruby-1.1.csv',
    'wicket-1.3.0-beta2.csv'
]

df_filtrado = df_resultados[df_resultados['Archivo'].isin(archivos_a_filtrar)]
df_filtrado

,Archivo,LOC,Attributes,Number of rows,Defective rate % (HueBug),Defective rate % (RealBug)
3,activemq-5.0.0.csv,142586,70,1884,4.35%,15.55%
1,derby-10.5.1.1.csv,533660,70,2705,6.65%,14.16%
22,groovy-1_6_BETA_1.csv,84199,70,821,14.25%,8.53%
5,hbase-0.94.0.csv,246541,70,1059,6.52%,20.59%
2,hive-0.9.0.csv,287310,70,1416,3.74%,19.99%
7,jruby-1.1.csv,105992,70,731,22.02%,11.9%
24,wicket-1.3.0-beta2.csv,109554,70,1763,17.3%,7.37%

================== Filtrado Final =====================

In [4]:
archivos_a_filtrar = [
    'activemq-5.0.0.csv',
    'derby-10.5.1.1.csv',
    'hive-0.9.0.csv',
    'wicket-1.3.0-beta2.csv'
]

df_filtrado = df_resultados[df_resultados['Archivo'].isin(archivos_a_filtrar)]
df_filtrado

,Archivo,LOC,Attributes,Number of rows,Defective rate % (HueBug),Defective rate % (RealBug)
3,activemq-5.0.0.csv,142586,70,1884,4.35%,15.55%
1,derby-10.5.1.1.csv,533660,70,2705,6.65%,14.16%
2,hive-0.9.0.csv,287310,70,1416,3.74%,19.99%
24,wicket-1.3.0-beta2.csv,109554,70,1763,17.3%,7.37%

## Preprocesamiento

- isNull / Missing values
- Duplicados
- Outlaiers
- Transformación de los datos - Normalización/Estandarización (MinMax, z-score)
- Balanceo de clases
> SMOTE segun papers
- Seleccion de caracteristicas (arbol de decision - CABOOST) 
- Reduccion de Dimensionalidad (PCA)
- Particion Train/Test

### Missing Values

In [8]:
df_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 3 to 24
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Archivo                     4 non-null      object
 1   LOC                         4 non-null      int64
 2   Attributes                  4 non-null      int64
 3   Number of rows              4 non-null      int64
 4   Defective rate % (HueBug)   4 non-null      object
 5   Defective rate % (RealBug)  4 non-null      object
dtypes: int64(3), object(3)
memory usage: 224.0+ bytes

In [ ]:
df_filtrado.isnull().sum()

Archivo                       0
LOC                           0
Attributes                    0
Number of rows                0
Defective rate % (HueBug)     0
Defective rate % (RealBug)    0
dtype: int64

### Duplicated

In [11]:
df_filtrado.duplicated()

3     False
1     False
2     False
24    False
dtype: bool