In [2]:
import pandas as pd

df = pd.read_csv("datasets/GlobalLandTemperaturesByMajorCity.csv")

In [3]:
df.head()

,dt,AverageTemperature,AverageTemperatureUncertainty,City,Country,Latitude,Longitude
0,1849-01-01,26.704,1.435,Abidjan,Côte D'Ivoire,5.63N,3.23W
1,1849-02-01,27.434,1.362,Abidjan,Côte D'Ivoire,5.63N,3.23W
2,1849-03-01,28.101,1.612,Abidjan,Côte D'Ivoire,5.63N,3.23W
3,1849-04-01,26.140,1.387,Abidjan,Côte D'Ivoire,5.63N,3.23W
4,1849-05-01,25.427,1.200,Abidjan,Côte D'Ivoire,5.63N,3.23W

In [4]:
df.shape

(239177, 7)

In [5]:
df.isnull().sum()

dt                                   0
AverageTemperature               11002
AverageTemperatureUncertainty    11002
City                                 0
Country                              0
Latitude                             0
Longitude                            0
dtype: int64

In [6]:
df[df.isnull().any(axis=1)]

,dt,AverageTemperature,AverageTemperatureUncertainty,City,Country,Latitude,Longitude
36,1852-01-01,NaN,NaN,Abidjan,Côte D'Ivoire,5.63N,3.23W
37,1852-02-01,NaN,NaN,Abidjan,Côte D'Ivoire,5.63N,3.23W
38,1852-03-01,NaN,NaN,Abidjan,Côte D'Ivoire,5.63N,3.23W
39,1852-04-01,NaN,NaN,Abidjan,Côte D'Ivoire,5.63N,3.23W
40,1852-05-01,NaN,NaN,Abidjan,Côte D'Ivoire,5.63N,3.23W
...,...,...,...,...,...,...,...
237089,1839-10-01,NaN,NaN,Xian,China,34.56N,108.97E
237090,1839-11-01,NaN,NaN,Xian,China,34.56N,108.97E
237091,1839-12-01,NaN,NaN,Xian,China,34.56N,108.97E
237422,1867-07-01,NaN,NaN,Xian,China,34.56N,108.97E
239176,2013-09-01,NaN,NaN,Xian,China,34.56N,108.97E

In [7]:
class_col = "City"
null_col = ["AverageTemperature","AverageTemperatureUncertainty"]
df_no_null = df[~df.isnull().any(axis=1)]
df_no_null

,dt,AverageTemperature,AverageTemperatureUncertainty,City,Country,Latitude,Longitude
0,1849-01-01,26.704,1.435,Abidjan,Côte D'Ivoire,5.63N,3.23W
1,1849-02-01,27.434,1.362,Abidjan,Côte D'Ivoire,5.63N,3.23W
2,1849-03-01,28.101,1.612,Abidjan,Côte D'Ivoire,5.63N,3.23W
3,1849-04-01,26.140,1.387,Abidjan,Côte D'Ivoire,5.63N,3.23W
4,1849-05-01,25.427,1.200,Abidjan,Côte D'Ivoire,5.63N,3.23W
...,...,...,...,...,...,...,...
239171,2013-04-01,12.563,1.823,Xian,China,34.56N,108.97E
239172,2013-05-01,18.979,0.807,Xian,China,34.56N,108.97E
239173,2013-06-01,23.522,0.647,Xian,China,34.56N,108.97E
239174,2013-07-01,25.251,1.042,Xian,China,34.56N,108.97E
239175,2013-08-01,24.528,0.840,Xian,China,34.56N,108.97E

In [8]:
df.groupby(class_col)[null_col].median()

             AverageTemperature  AverageTemperatureUncertainty
City
Abidjan                 26.2240                         0.5010
Addis Abeba             17.2930                         0.7250
Ahmadabad               27.2575                         0.5975
Aleppo                  17.6120                         0.6350
Alexandria              20.4635                         0.5670
...                         ...                            ...
Tokyo                   13.1115                         0.3060
Toronto                  5.9150                         0.6250
Umm Durman              30.2655                         0.6685
Wuhan                   17.4015                         0.4755
Xian                    11.8380                         0.8185

[100 rows x 2 columns]

In [9]:
median_avgTemp = df.groupby(class_col)[null_col].transform("median")
median_avgTemp

        AverageTemperature  AverageTemperatureUncertainty
0                   26.224                         0.5010
1                   26.224                         0.5010
2                   26.224                         0.5010
3                   26.224                         0.5010
4                   26.224                         0.5010
...                    ...                            ...
239172              11.838                         0.8185
239173              11.838                         0.8185
239174              11.838                         0.8185
239175              11.838                         0.8185
239176              11.838                         0.8185

[239177 rows x 2 columns]

In [10]:
new_df = df[null_col].fillna(median_avgTemp)

In [11]:
new_df.tail()

        AverageTemperature  AverageTemperatureUncertainty
239172              18.979                         0.8070
239173              23.522                         0.6470
239174              25.251                         1.0420
239175              24.528                         0.8400
239176              11.838                         0.8185

In [12]:
new_df.isnull().sum()

AverageTemperature               0
AverageTemperatureUncertainty    0
dtype: int64

In [13]:
export_df = df.copy()

export_df[null_col] = new_df

export_df

,dt,AverageTemperature,AverageTemperatureUncertainty,City,Country,Latitude,Longitude
0,1849-01-01,26.704,1.4350,Abidjan,Côte D'Ivoire,5.63N,3.23W
1,1849-02-01,27.434,1.3620,Abidjan,Côte D'Ivoire,5.63N,3.23W
2,1849-03-01,28.101,1.6120,Abidjan,Côte D'Ivoire,5.63N,3.23W
3,1849-04-01,26.140,1.3870,Abidjan,Côte D'Ivoire,5.63N,3.23W
4,1849-05-01,25.427,1.2000,Abidjan,Côte D'Ivoire,5.63N,3.23W
...,...,...,...,...,...,...,...
239172,2013-05-01,18.979,0.8070,Xian,China,34.56N,108.97E
239173,2013-06-01,23.522,0.6470,Xian,China,34.56N,108.97E
239174,2013-07-01,25.251,1.0420,Xian,China,34.56N,108.97E
239175,2013-08-01,24.528,0.8400,Xian,China,34.56N,108.97E
239176,2013-09-01,11.838,0.8185,Xian,China,34.56N,108.97E

In [14]:
export_df.to_csv("inc-a_GlobalLandTemperaturesByMajorCity.csv")